FROM node:10.16

WORKDIR /usr/src/backend

RUN apt-get update \
  && apt-get install -y build-essential \
  && apt-get install -y python \
  && apt-get dist-upgrade -y \
  && apt-get clean \
  && echo 'Finished installing dependencies'

COPY . .

RUN npm install --production

ENV NODE_ENV production
ENV PORT 4000
EXPOSE 4000

CMD ["npm", "start"]